spring:
  application:
    name: BukuKeuangan1

  datasource:
    # Tambahkan protokol jdbc:sqlserver:// dan akhiri dengan konfigurasi keamanan
    url: jdbc:sqlserver://latihansql.database.windows.net:1433;databaseName=sqldemoexercise;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: user01
    password: Admin1234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080  # Ubah ke 8081 jika 8080 masih dipakai oleh Oracle VM Anda
  
  
  